import {
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Command,
  File,
  FileText,
  Github,
  LoaderCircle,
  LucideProps,
  Menu,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
} from "lucide-react"

export type Icon = typeof ArrowRight

export const Icons = {
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  command: Command,
  file: File,
  fileText: FileText,
  github: Github,
  loader: LoaderCircle,
  menu: Menu,
  moon: Moon,
  moreVertical: MoreVertical,
  pizza: Pizza,
  plus: Plus,
  settings: Settings,
  sun: SunMedium,
  trash: Trash,
  twitter: Twitter,
  user: User,
  x: X,
} 